### ISSUE TITLE
unable to run example command 

### ISSUE THREAD

**Issue by Anupam-5** [baker-laboratory/RoseTTAFold-All-Atom#116]
I have followed the steps in the tutorial and done everything as directed in it but getting an error on running the example command. i have gone through the previous issues reported regarding it but am confused what to do. Kindly help what should I do to run it successfully. I am providing below  the command log and the command i passed. Please help!!

(RFAA) kinshuk@kinshuk-lab:/media/kinshuk/My Book/rossettafold/RoseTTAFold-All-Atom$ python -m rf2aa.run_inference --config-name protein
/home/kinshuk/anaconda3/envs/RFAA/lib/python3.10/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'protein': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
Using the cif atom ordering for TRP.
./make_msa.sh examples/protein/7u7w_A.fasta 7u7w_protein/A 4 64  pdb100_2021Mar03/pdb100_2021Mar03
Predicting: 100%|██████████████████████████| 1/1 [00:01<00:00,  1.02s/sequences]
Running HHblits against UniRef30 with E-value cutoff 1e-10
- 10:43:42.153 WARNING: Ignoring unknown option Book/rossettafold/RoseTTAFold-All-Atom/UniRef30_2023_02/UniRef30_2023_02

- 10:43:42.153 ERROR: In /opt/conda/conda-bld/hhsuite_1709621322429/work/src/ffindexdatabase.cpp:11: FFindexDatabase:

- 10:43:42.153 ERROR: 	could not open file '/media/kinshuk_cs219.ffdata'

- 10:43:42.175 INFO: Input file = 7u7w_protein/A/hhblits/t000_.1e-10.a3m

- 10:43:42.175 INFO: Output file = 7u7w_protein/A/hhblits/t000_.1e-10.id90cov75.a3m

- 10:43:42.175 ERROR: In /opt/conda/conda-bld/hhsuite_1709621322429/work/src/hhfilter.cpp:177: main:

- 10:43:42.175 ERROR: 	could not open file '7u7w_protein/A/hhblits/t000_.1e-10.a3m'

- 10:43:42.179 INFO: Input file = 7u7w_protein/A/hhblits/t000_.1e-10.a3m

- 10:43:42.179 INFO: Output file = 7u7w_protein/A/hhblits/t000_.1e-10.id90cov50.a3m

- 10:43:42.179 ERROR: In /opt/conda/conda-bld/hhsuite_1709621322429/work/src/hhfilter.cpp:177: main:

- 10:43:42.179 ERROR: 	could not open file '7u7w_protein/A/hhblits/t000_.1e-10.a3m'

grep: 7u7w_protein/A/hhblits/t000_.1e-10.id90cov75.a3m: No such file or directory
grep: 7u7w_protein/A/hhblits/t000_.1e-10.id90cov50.a3m: No such file or directory
Running HHblits against UniRef30 with E-value cutoff 1e-6
- 10:43:42.191 WARNING: Ignoring unknown option Book/rossettafold/RoseTTAFold-All-Atom/UniRef30_2023_02/UniRef30_2023_02

- 10:43:42.191 ERROR: In /opt/conda/conda-bld/hhsuite_1709621322429/work/src/ffindexdatabase.cpp:11: FFindexDatabase:

- 10:43:42.191 ERROR: 	could not open file '/media/kinshuk_cs219.ffdata'

- 10:43:42.195 INFO: Input file = 7u7w_protein/A/hhblits/t000_.1e-6.a3m

- 10:43:42.195 INFO: Output file = 7u7w_protein/A/hhblits/t000_.1e-6.id90cov75.a3m

- 10:43:42.195 ERROR: In /opt/conda/conda-bld/hhsuite_1709621322429/work/src/hhfilter.cpp:177: main:

- 10:43:42.195 ERROR: 	could not open file '7u7w_protein/A/hhblits/t000_.1e-6.a3m'

- 10:43:42.199 INFO: Input file = 7u7w_protein/A/hhblits/t000_.1e-6.a3m

- 10:43:42.200 INFO: Output file = 7u7w_protein/A/hhblits/t000_.1e-6.id90cov50.a3m

- 10:43:42.200 ERROR: In /opt/conda/conda-bld/hhsuite_1709621322429/work/src/hhfilter.cpp:177: main:

- 10:43:42.200 ERROR: 	could not open file '7u7w_protein/A/hhblits/t000_.1e-6.a3m'

grep: 7u7w_protein/A/hhblits/t000_.1e-6.id90cov75.a3m: No such file or directory
grep: 7u7w_protein/A/hhblits/t000_.1e-6.id90cov50.a3m: No such file or directory
Running HHblits against UniRef30 with E-value cutoff 1e-3
- 10:43:42.211 WARNING: Ignoring unknown option Book/rossettafold/RoseTTAFold-All-Atom/UniRef30_2023_02/UniRef30_2023_02

- 10:43:42.211 ERROR: In /opt/conda/conda-bld/hhsuite_1709621322429/work/src/ffindexdatabase.cpp:11: FFindexDatabase:

- 10:43:42.211 ERROR: 	could not open file '/media/kinshuk_cs219.ffdata'

- 10:43:42.216 INFO: Input file = 7u7w_protein/A/hhblits/t000_.1e-3.a3m

- 10:43:42.216 INFO: Output file = 7u7w_protein/A/hhblits/t000_.1e-3.id90cov75.a3m

- 10:43:42.216 ERROR: In /opt/conda/conda-bld/hhsuite_1709621322429/work/src/hhfilter.cpp:177: main:

- 10:43:42.216 ERROR: 	could not open file '7u7w_protein/A/hhblits/t000_.1e-3.a3m'

- 10:43:42.220 INFO: Input file = 7u7w_protein/A/hhblits/t000_.1e-3.a3m

- 10:43:42.220 INFO: Output file = 7u7w_protein/A/hhblits/t000_.1e-3.id90cov50.a3m

- 10:43:42.220 ERROR: In /opt/conda/conda-bld/hhsuite_1709621322429/work/src/hhfilter.cpp:177: main:

- 10:43:42.220 ERROR: 	could not open file '7u7w_protein/A/hhblits/t000_.1e-3.a3m'

grep: 7u7w_protein/A/hhblits/t000_.1e-3.id90cov75.a3m: No such file or directory
grep: 7u7w_protein/A/hhblits/t000_.1e-3.id90cov50.a3m: No such file or directory
Running HHblits against BFD with E-value cutoff 1e-3
- 10:43:42.231 WARNING: Ignoring unknown option Book/rossettafold/RoseTTAFold-All-Atom/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt

- 10:43:42.231 ERROR: In /opt/conda/conda-bld/hhsuite_1709621322429/work/src/ffindexdatabase.cpp:11: FFindexDatabase:

- 10:43:42.231 ERROR: 	could not open file '/media/kinshuk_cs219.ffdata'

- 10:43:42.236 INFO: Input file = 7u7w_protein/A/hhblits/t000_.1e-3.bfd.a3m

- 10:43:42.236 INFO: Output file = 7u7w_protein/A/hhblits/t000_.1e-3.bfd.id90cov75.a3m

- 10:43:42.236 ERROR: In /opt/conda/conda-bld/hhsuite_1709621322429/work/src/hhfilter.cpp:177: main:

- 10:43:42.236 ERROR: 	could not open file '7u7w_protein/A/hhblits/t000_.1e-3.bfd.a3m'

- 10:43:42.240 INFO: Input file = 7u7w_protein/A/hhblits/t000_.1e-3.bfd.a3m

- 10:43:42.240 INFO: Output file = 7u7w_protein/A/hhblits/t000_.1e-3.bfd.id90cov50.a3m

- 10:43:42.240 ERROR: In /opt/conda/conda-bld/hhsuite_1709621322429/work/src/hhfilter.cpp:177: main:

- 10:43:42.240 ERROR: 	could not open file '7u7w_protein/A/hhblits/t000_.1e-3.bfd.a3m'

grep: 7u7w_protein/A/hhblits/t000_.1e-3.bfd.id90cov75.a3m: No such file or directory
grep: 7u7w_protein/A/hhblits/t000_.1e-3.bfd.id90cov50.a3m: No such file or directory
cp: cannot stat '7u7w_protein/A/hhblits/t000_.1e-3.bfd.id90cov50.a3m': No such file or directory
Running PSIPRED
Running hhsearch
cat: 7u7w_protein/A/t000_.ss2: No such file or directory
cat: 7u7w_protein/A/t000_.msa0.a3m: No such file or directory
- 10:43:42.508 ERROR: Error in /opt/conda/conda-bld/hhsuite_1709621322429/work/src/hhfunc.cpp:16: ReadQueryFile:

- 10:43:42.508 ERROR: 	7u7w_protein/A/t000_.msa0.ss2.a3m is empty!

Error executing job with overrides: []
Traceback (most recent call last):
  File "/media/kinshuk/My Book/rossettafold/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 206, in main
    runner.infer()
  File "/media/kinshuk/My Book/rossettafold/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 153, in infer
    self.parse_inference_config()
  File "/media/kinshuk/My Book/rossettafold/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 46, in parse_inference_config
    protein_input = generate_msa_and_load_protein(
  File "/media/kinshuk/My Book/rossettafold/RoseTTAFold-All-Atom/rf2aa/data/protein.py", line 93, in generate_msa_and_load_protein
    return load_protein(str(msa_file), str(hhr_file), str(atab_file), model_runner)
  File "/media/kinshuk/My Book/rossettafold/RoseTTAFold-All-Atom/rf2aa/data/protein.py", line 56, in load_protein
    msa, ins, taxIDs = parse_a3m(msa_file)
  File "/media/kinshuk/My Book/rossettafold/RoseTTAFold-All-Atom/rf2aa/data/parsers.py", line 415, in parse_a3m
    fstream = open(filename, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '7u7w_protein/A/t000_.msa0.a3m'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by Wzx0818** [comment]
Hi! I also meet the same question, have you solved it?
Could you please give me some help?

**Comment by jscgh** [comment]
> Hi! I also meet the same question, have you solved it? Could you please give me some help?

What is your error log? That error is caused by inaccessible uniref30 dbs.

Relevant errors from OP:

```
10:43:42.153 WARNING: Ignoring unknown option Book/rossettafold/RoseTTAFold-All-Atom/UniRef30_2023_02/UniRef30_2023_02

10:43:42.153 ERROR: In /opt/conda/conda-bld/hhsuite_1709621322429/work/src/ffindexdatabase.cpp:11: FFindexDatabase:

10:43:42.153 ERROR: could not open file '/media/kinshuk_cs219.ffdata'
```

**Comment by Wzx0818** [comment]
Hi！Here is the error I met
FileNotFoundError: [Errno 2] No such file or directory: '7qxr/A/t000_.msa0.a3m'

In the directory 7qxr/A/, the existing files are t000_.msa0.ss2.a3m and t000_.ss2, but t000_.msa0.a3m is missing.

#169

**Comment by jscgh** [comment]
> Hi！Here is the error I met FileNotFoundError: [Errno 2] No such file or directory: '7qxr/A/t000_.msa0.a3m'
> 
> In the directory 7qxr/A/, the existing files are t000_.msa0.ss2.a3m and t000_.ss2, but t000_.msa0.a3m is missing.
> 
> [#169](https://github.com/baker-laboratory/RoseTTAFold-All-Atom/issues/169)

Yes, this because hhblits is failing to run. I've replied in your issue https://github.com/baker-laboratory/RoseTTAFold-All-Atom/issues/169#issuecomment-2974840351
