### ISSUE TITLE
`expand_multi_msa()` fails for certain inputs

### ISSUE THREAD

**Issue by amorehead** [baker-laboratory/RoseTTAFold-All-Atom#30]
Hello.

When I tried predicting a protein-ligand complex structure using the attached complex's files, I received the following error call stack. I cannot identify any obvious issues with the inputs on my end.

[Failed_Inputs.zip](https://github.com/baker-laboratory/RoseTTAFold-All-Atom/files/14592867/Failed_Inputs.zip)

```bash
Traceback (most recent call last):
  File "/home/acmwhb/Repositories/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 206, in
 main
    runner.infer()
  File "/home/acmwhb/Repositories/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 153, in
 infer
    self.parse_inference_config()
  File "/home/acmwhb/Repositories/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 93, in 
parse_inference_config
    raw_data = merge_all(protein_inputs, na_inputs, sm_inputs, residues_to_atomize, deterministic=self.deterministic)
  File "/home/acmwhb/Repositories/RoseTTAFold-All-Atom/rf2aa/data/merge_inputs.py", line 169
, in merge_all
    protein_inputs, protein_chain_lengths = merge_protein_inputs(protein_inputs, deterministic=deterministic)
  File "/home/acmwhb/Repositories/RoseTTAFold-All-Atom/rf2aa/data/merge_inputs.py", line 48,
 in merge_protein_inputs
    a3m_out = expand_multi_msa(a3m_out, unique_hashes, hash_list, unique_lengths_list, lengths_list)
  File "/home/acmwhb/Repositories/RoseTTAFold-All-Atom/rf2aa/data/data_loader_utils.py", lin
e 787, in expand_multi_msa
    assert(a3m['msa'].shape[1]==sum(Ls_in))
AssertionError
```

**Comment by amorehead** [comment]
I found (for my custom inputs) this seems to be caused by the bug described in https://github.com/baker-laboratory/RoseTTAFold-All-Atom/issues/47. Fixing this bug in the way described here resolves this AssertionError on my end.
