### ISSUE TITLE
Error in python -m rf2aa.run_inference --config-name protein_sm

### ISSUE THREAD

**Issue by xie-yun-ai** [baker-laboratory/RoseTTAFold-All-Atom#36]
Error executing job with overrides: []
Traceback (most recent call last):
  File "/Data/RoseTTAFold2NA/RoseTTAFold-All-Atom-2/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 206, in main
    runner.infer()
  File "/Data/RoseTTAFold2NA/RoseTTAFold-All-Atom-2/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 153, in infer
    self.parse_inference_config()
  File "/Data/RoseTTAFold2NA/RoseTTAFold-All-Atom-2/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 81, in parse_inference_config
    sm_input = load_small_molecule(
  File "/Data/RoseTTAFold2NA/RoseTTAFold-All-Atom-2/RoseTTAFold-All-Atom/rf2aa/data/small_molecule.py", line 16, in load_small_molecule
    obmol, msa, ins, xyz, mask = parse_mol(
  File "/Data/RoseTTAFold2NA/RoseTTAFold-All-Atom-2/RoseTTAFold-All-Atom/rf2aa/data/parsers.py", line 787, in parse_mol
    ff.FastRotorSearch()
AttributeError: 'OBForceField' object has no attribute 'FastRotorSearch'

This error has occurred. May I ask if anyone has encountered such a problem and for what reason

**Comment by knight-qs** [comment]
I referred to your solution ideas every step. After the monomerent prediction test was completed, I also tried `python -m rf2aa.run_inference --config-name protein_sm`, but surprisingly, I did not report any error. The rmsd of the predicted structure and the crystal structure on the pdb database is 0.545

![image](https://github.com/baker-laboratory/RoseTTAFold-All-Atom/assets/101613540/6b8a7970-2c2a-43a4-8d39-d698b3679672)

![image](https://github.com/baker-laboratory/RoseTTAFold-All-Atom/assets/101613540/27389a25-d2c6-4f36-b8db-ba87a4cfa6d1)

**Comment by RyanGarciaLI** [comment]
I also have this problem. The OpenBabel compilation may have some problems with Python binding. After making sure eigen3 is installed correctly. I rebuild OpenBabel using `cmake -DRUN_SWIG=ON -DPYTHON_BINDINGS=ON -DEIGEN3_INCLUDE_DIR=/usr/local/include/eigen3/ ..`. Then it works.

**Comment by rjacak-invenra** [comment]
I ran into this issue, as well.  Unfortunately, on Ubuntu 20.04, recompiling OpenBabel did not work for me.  Installing the openbabel Python module using apt instead of pip did work though.
$ sudo apt-get install python3-openbabel

I think it might be related to [this openbabel issue](https://github.com/openbabel/openbabel/issues/2408) which stems from the use of an unusual version number (3.1.1.1).  When installing through apt, you get version 3.1.1+dfsg-6ubuntu5.
