### ISSUE TITLE
OSError after python -m rf2aa.run_inference --config-name protein

### ISSUE THREAD

**Issue by PiotrP95** [baker-laboratory/RoseTTAFold-All-Atom#38]
Hi everyone! I am new to this, with computer science and programming I don't have much experience, so I apologise if my problem is stupid or I do not give enough information. I am trying tu run RFAA on the cluster my lab is using, after using **python -m rf2aa.run_inference --config-name protein** I got this. Don't really know what to do. Thanks!

**(RFAA) [athena][.................... RoseTTAFold-All-Atom]$ python -m rf2aa.run_inference --config-name protein**
/net/pr2/projects/plgrid/plggmrslab/Piotr/RoseTTAFold-All-Atom/mambaforge/envs/RFAA/lib/python3.10/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'protein': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
Using the cif atom ordering for TRP.
Error executing job with overrides: []
Traceback (most recent call last):
  File "/net/pr2/projects/plgrid/plggmrslab/Piotr/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 205, in main
    runner = ModelRunner(config)
  File "/net/pr2/projects/plgrid/plggmrslab/Piotr/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 28, in __init__
    read_data(config.database_params.hhdb+'_pdb.ffdata'))
  File "/net/pr2/projects/plgrid/plggmrslab/Piotr/RoseTTAFold-All-Atom/rf2aa/ffindex.py", line 32, in read_data
    data = mmap.mmap(fh.fileno(), 0, access=mmap.ACCESS_READ)
OSError: [Errno 12] Cannot allocate memory

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by liudongliangHI** [comment]
This seems to be just because your computer is low on memory. 
Perhaps you can contact your administrator to allocate you more memory.
