### ISSUE TITLE
No such file or directory: 'pdb100_2022Apr19/pdb100_2022Apr19_pdb.ffindex'

### ISSUE THREAD

**Issue by blauemond** [baker-laboratory/RoseTTAFold-All-Atom#4]
When I run the followings:
`singularity run SE3nv-20240131.sif -m rf2aa.run_inference --config-name protein`
It reports this error:
```
Error executing job with overrides: [] 
Traceback (most recent call last): 
  File "/xcfhome/yzmeng/tools/fold/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 205, in main
    runner = ModelRunner(config)
  File "/xcfhome/yzmeng/tools/fold/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 27, in __init__
    self.ffdb = FFindexDB(read_index(config.database_params.hhdb+'_pdb.ffindex'),
  File "/xcfhome/yzmeng/tools/fold/RoseTTAFold-All-Atom/rf2aa/ffindex.py", line 21, in read_index
    fh = open(ffindex_filename, "r")
FileNotFoundError: [Errno 2] No such file or directory: 'pdb100_2022Apr19/pdb100_2022Apr19_pdb.ffindex''
```
But after I manually changed the PDB database path name in `base.yaml`, the error will still occur.
How can I solve this problem, or is there any other way to use it.

**Comment by Takk522** [comment]
老哥，你这个bug解决了吗，我也遇到这个问题了

**Comment by Rolando-at-Arzeda** [comment]
same here ..

apptainer run SE3nv-20240131.sif -m rf2aa.run_inference --config-name protein.yaml --config-dir /home/ubuntu/progs/RoseTTAFold-All-Atom/rf2aa/

INFO:    squashfs image was compressed with lz4, if it failed to run, please contact image's author
INFO:    squashfs image was compressed with lz4, if it failed to run, please contact image's author

/usr/lib/python3.10/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'protein.yaml': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
Using the cif atom ordering for TRP.
Error executing job with overrides: []
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/progs/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 209, in <module>
    main()
  File "/usr/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/usr/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/usr/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/usr/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/usr/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/usr/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/usr/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/usr/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/usr/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/ubuntu/progs/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 205, in main
    runner = ModelRunner(config)
  File "/home/ubuntu/progs/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 27, in __init__
    self.ffdb = FFindexDB(read_index(config.database_params.hhdb+'_pdb.ffindex'),
  File "/home/ubuntu/progs/RoseTTAFold-All-Atom/rf2aa/ffindex.py", line 21, in read_index
    fh = open(ffindex_filename, "r")

**FileNotFoundError: [Errno 2] No such file or directory: 'pdb100_2022Apr19/pdb100_2022Apr19_pdb.ffindex'**

**Comment by Rolando-at-Arzeda** [comment]
Hi
If by any chance you are using a symlink instead of the real directory, it will not work well with the container, directories and files should be "real"

**Comment by denizkavi** [comment]
I am keeping my dbs in /data/ so I modified my config at "rf2aa/config/inference/base.yaml" to include that path:
```
job_name: "structure_prediction"
output_path: ""
checkpoint_path: RFAA_paper_weights.pt
database_params:
  sequencedb: ""
  hhdb: "/data/pdb100_2021Mar03/pdb100_2021Mar03"
  command: make_msa.sh
  num_cpus: 4
  mem: 64
```

Then, you can bind your path to the container to use:
sudo /usr/bin/apptainer run --bind /data:/data SE3nv-20240131.sif -m rf2aa.run_inference --config-name protein

**Comment by r-krishna** [comment]
hello @amorehead has created a PR that installs dependencies using mamba (this is now merged in main). let me know if this solves your problem
