### ISSUE TITLE
Small molecule without protein causes error

### ISSUE THREAD

**Issue by tydingcw** [baker-laboratory/RoseTTAFold-All-Atom#41]
If you try to predict, just examples/small_molecule/NSW_ideal.sdf for example, you get this error:

Traceback (most recent call last):
  File "/home/tydingcw/git_repos/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 206, in main
    runner.infer()
  File "/home/tydingcw/git_repos/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 154, in infer
    input_feats = self.construct_features()
  File "/home/tydingcw/git_repos/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 113, in construct_features
    return self.raw_data.construct_features(self)
  File "/home/tydingcw/git_repos/RoseTTAFold-All-Atom/rf2aa/data/data_loader.py", line 131, in construct_features
    xyz_t_frame = xyz_t_to_frame_xyz(self.xyz_t[None], self.msa[0], self.atom_frames)
  File "/home/tydingcw/git_repos/RoseTTAFold-All-Atom/rf2aa/util.py", line 235, in xyz_t_to_frame_xyz
    return xyz_t_to_frame_xyz_sm_mask(xyz_t, is_sm, atom_frames)
  File "/home/tydingcw/git_repos/RoseTTAFold-All-Atom/rf2aa/util.py", line 256, in xyz_t_to_frame_xyz_sm_mask
    B, T, atom_L, natoms, _ = atom_crds_t.shape
ValueError: too many values to unpack (expected 5)

**Comment by smilenaderi** [comment]
I'm facing the same issue
