### ISSUE TITLE
"sequence ss_pred contains no residues" Error

### ISSUE THREAD

**Issue by denizkavi** [baker-laboratory/RoseTTAFold-All-Atom#56]
Get the following error running the example protein config:
```
- 04:11:56.079 ERROR: In /opt/conda/conda-bld/hhsuite_1709621322429/work/src/hhalignment.cpp:223: Read:

- 04:11:56.079 ERROR:   sequence ss_pred contains no residues.
```
Full log:
```
(RFAA)~/RoseTTAFold-All-Atom$ python -m rf2aa.run_inference --config-name protein
/opt/conda/envs/RFAA/lib/python3.10/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'protein': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
Using the cif atom ordering for TRP.
./make_msa.sh examples/protein/7s69_A.fasta 7u7w_protein/A 4 64 /data/UniRef30_2021_06/UniRef30_2021_06 /data/pdb100_2021Mar03/pdb100_2021Mar03
Running HHblits against UniRef30 with E-value cutoff 1e-10
- 03:21:44.800 INFO: Input file = 7u7w_protein/A/hhblits/t000_.1e-10.a3m

- 03:21:44.800 INFO: Output file = 7u7w_protein/A/hhblits/t000_.1e-10.id90cov75.a3m

- 03:21:44.832 INFO: Input file = 7u7w_protein/A/hhblits/t000_.1e-10.a3m

- 03:21:44.832 INFO: Output file = 7u7w_protein/A/hhblits/t000_.1e-10.id90cov50.a3m

Running HHblits against UniRef30 with E-value cutoff 1e-6
- 03:27:33.879 INFO: Input file = 7u7w_protein/A/hhblits/t000_.1e-6.a3m

- 03:27:33.879 INFO: Output file = 7u7w_protein/A/hhblits/t000_.1e-6.id90cov75.a3m

- 03:27:33.946 INFO: Input file = 7u7w_protein/A/hhblits/t000_.1e-6.a3m

- 03:27:33.946 INFO: Output file = 7u7w_protein/A/hhblits/t000_.1e-6.id90cov50.a3m

Running HHblits against UniRef30 with E-value cutoff 1e-3
- 03:33:29.275 INFO: Input file = 7u7w_protein/A/hhblits/t000_.1e-3.a3m

- 03:33:29.275 INFO: Output file = 7u7w_protein/A/hhblits/t000_.1e-3.id90cov75.a3m

- 03:33:29.352 INFO: Input file = 7u7w_protein/A/hhblits/t000_.1e-3.a3m

- 03:33:29.352 INFO: Output file = 7u7w_protein/A/hhblits/t000_.1e-3.id90cov50.a3m

Running HHblits against BFD with E-value cutoff 1e-3
- 04:11:39.823 INFO: Input file = 7u7w_protein/A/hhblits/t000_.1e-3.bfd.a3m

- 04:11:39.823 INFO: Output file = 7u7w_protein/A/hhblits/t000_.1e-3.bfd.id90cov75.a3m

- 04:11:40.910 INFO: Input file = 7u7w_protein/A/hhblits/t000_.1e-3.bfd.a3m

- 04:11:40.910 INFO: Output file = 7u7w_protein/A/hhblits/t000_.1e-3.bfd.id90cov50.a3m

Running PSIPRED
Running hhsearch
- 04:11:56.079 ERROR: In /opt/conda/conda-bld/hhsuite_1709621322429/work/src/hhalignment.cpp:223: Read:

- 04:11:56.079 ERROR:   sequence ss_pred contains no residues.

Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/ubuntu/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 206, in main
    runner.infer()
  File "/home/ubuntu/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 153, in infer
    self.parse_inference_config()
  File "/home/ubuntu/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 46, in parse_inference_config
    protein_input = generate_msa_and_load_protein(
  File "/home/ubuntu/RoseTTAFold-All-Atom/rf2aa/data/protein.py", line 93, in generate_msa_and_load_protein
    return load_protein(str(msa_file), str(hhr_file), str(atab_file), model_runner)
  File "/home/ubuntu/RoseTTAFold-All-Atom/rf2aa/data/protein.py", line 66, in load_protein
    xyz_t, t1d, mask_t, _ = get_templates(
  File "/home/ubuntu/RoseTTAFold-All-Atom/rf2aa/data/protein.py", line 30, in get_templates
    ) = parse_templates_raw(ffdb, hhr_fn=hhr_fn, atab_fn=atab_fn)
  File "/home/ubuntu/RoseTTAFold-All-Atom/rf2aa/data/parsers.py", line 628, in parse_templates_raw
    for l in open(atab_fn, "r").readlines():
FileNotFoundError: [Errno 2] No such file or directory: '7u7w_protein/A/t000_.atab'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by liudongliangHI** [comment]
Maybe you can refer to this:

https://github.com/baker-laboratory/RoseTTAFold-All-Atom/issues/31#issuecomment-1997639969
