### ISSUE TITLE
Error with Protein/Nucleic acid complex prediction: "Class values must be smaller than num_classes"

### ISSUE THREAD

**Issue by ebettler** [baker-laboratory/RoseTTAFold-All-Atom#57]
Hi,
thank you for your great work !
I've successfully installed RFAA and run an example with 4DFR and MTX ligand.
But with Protein/Nucleic acid complex, i've this error message:
[...]
Running HHblits against BFD with E-value cutoff 1e-3
- 21:55:16.080 INFO: Input file = delta60_protein_nucleic_hdv/A/hhblits/t000_.1e-3.bfd.a3m
- 21:55:16.080 INFO: Output file = delta60_protein_nucleic_hdv/A/hhblits/t000_.1e-3.bfd.id90cov75.a3m
- 21:55:16.100 INFO: Input file = delta60_protein_nucleic_hdv/A/hhblits/t000_.1e-3.bfd.a3m
- 21:55:16.100 INFO: Output file = delta60_protein_nucleic_hdv/A/hhblits/t000_.1e-3.bfd.id90cov50.a3m

Running PSIPRED
Running hhsearch
Error executing job with overrides: []
Traceback (most recent call last):
  File "/softwares/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 206, in main
    runner.infer()
  File "/softwares/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 154, in infer
    input_feats = self.construct_features()
  File "/softwares/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 113, in construct_features
    return self.raw_data.construct_features(self)
  File "/softwares/RoseTTAFold-All-Atom/rf2aa/data/data_loader.py", line 110, in construct_features
    seq, msa_clust, msa_seed, msa_extra, mask_pos = MSAFeaturize(
  File "/softwares/RoseTTAFold-All-Atom/rf2aa/data/data_loader_utils.py", line 95, in MSAFeaturize
    raw_profile = torch.nn.functional.one_hot(msa, num_classes=ChemData().NAATOKENS) # N x L x NAATOKENS
RuntimeError: Class values must be smaller than num_classes.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

Any idea what's wrong ?
BR,

**Comment by ebettler** [comment]
Problem solved.
A mistake in the yaml file (same chain A for protein and nucleic acid). Also be sure to delete previous output files !

**Comment by Mingdi-W** [comment]
I met this issue for a long time. Should I change base.yaml or something? please help me, thx soooo much.

**Comment by ebettler** [comment]
The example is working fine but with my protein and my rna, not ! MSA seems to be OK. So yes, if someone has an idea...

**Comment by Mingdi-W** [comment]
Thx for ur immediate answer!!!  The example 7u7W and dna is working perfectly great. But when I tried my protein and rna , always this issue even I copy directly the seq to the 7U7W files. Hope someone can give solution!!!

**Comment by sherryliu987** [comment]
I am also facing this issue for protein-rna complexes.

**Comment by smilenaderi** [comment]
I'm facing this issue with small molecules too

**Comment by Jh-SYSU** [comment]
I am also facing this issue.

**Comment by jeramon** [comment]
I've been running into the same problem and I did some debugging. Each amino acid and base gets a number. U is supposed to be '30' according to chemical.py, but for some reason gets '85.' This then trips up one_hot because ChemData().NAATOKENS is 80, which is less than 85. 

I solved the problem by brute force - changing all instances of 85 in 'msa' to 30. In /softwares/RoseTTAFold-All-Atom/rf2aa/data/data_loader_utils.py":

`msa[msa == 85] = 30`

just before one_hot is called in line 95. I can now get past this error but other ones do pop up. So I am not sure this is the solution, just posting this in case this debugging info helps someone get to the next step.

**Comment by fglaser** [comment]
Get the same problem here too,

Running PSIPRED
Running hhsearch
cat: 2ANN/A/t000_.ss2: No such file or directory
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/fabian/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 206, in main
    runner.infer()
  File "/home/fabian/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 154, in infer
    input_feats = self.construct_features()
  File "/home/fabian/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 113, in construct_features
    return self.raw_data.construct_features(self)
  File "/home/fabian/RoseTTAFold-All-Atom/rf2aa/data/data_loader.py", line 110, in construct_features
    seq, msa_clust, msa_seed, msa_extra, mask_pos = MSAFeaturize(
  File "/home/fabian/RoseTTAFold-All-Atom/rf2aa/data/data_loader_utils.py", line 95, in MSAFeaturize
    raw_profile = torch.nn.functional.one_hot(msa, num_classes=ChemData().NAATOKENS) # N x L x NAATOKENS
RuntimeError: Class values must be smaller than num_classes.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by sherryliu987** [comment]
For me, the error was due to using T/U in RNA/DNA sequences

**Comment by fglaser** [comment]
Oh I see, thanks a lot. 
Will the RNA - protein modeling be supported?

Thanks!
Fabian
