### ISSUE TITLE
No module named 'hydra'

### ISSUE THREAD

**Issue by cron-weasley** [baker-laboratory/RoseTTAFold-All-Atom#58]
Dear Auth,
After I finished install RoseTTAFold-All-Atom,I try to run:
python -m rf2aa.run_inference --config-name protein
I got an error of:

(RFAA) [chenziyang@mgmt RoseTTAFold-All-Atom-main]$ python -m rf2aa.run_inference --config-name protein
Traceback (most recent call last):
  File "/share/home/chenziyang/.conda/envs/RFAA/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/share/home/chenziyang/.conda/envs/RFAA/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/share/home/chenziyang/RoseTTAFold-All-Atom-main/rf2aa/run_inference.py", line 2, in <module>
    import hydra
ModuleNotFoundError: No module named 'hydra'

I check with pip list found that my mamba python environment only install hydra-core, then I try to install hydra-2.5 with pip install hydra, but failed.

I found that hydra-2.5 support python 3.8 and 3.9 but RoseTTAFold-All-Atom using python 3.10 installed env.
Where I am wrong?  And how to install hydra in RoseTTAFold-All-Atom?
Thanks a lot!

**Comment by amorehead** [comment]
`hydra-core` is the dependency you need, not `hydra` (even though confusingly the Python module installed by `hydra-core` is labeled `hydra`). It seems your Conda environment is not properly activated, since it should be picking up on `hydra` from your installed copy of `hydra-core`.

**Comment by cron-weasley** [comment]
> `hydra-core` is the dependency you need, not `hydra` (even though confusingly the Python module installed by `hydra-core` is labeled `hydra`). It seems your Conda environment is not properly activated, since it should be picking up on `hydra` from your installed copy of `hydra-core`.

Yes, I found the problem, It's my fault, please close my issue, Thanks!

**Comment by amorehead** [comment]
Hi, @cron-weasley. Great to hear your issue is resolved. I believe you'll have to close the issue, since I do not have the ability to on my end.

**Comment by zehanna** [comment]
Hi @cron-weasley, would you mind sharing how you fixed that error? I'm facing the same issue. Thanks a lot in advance!
