### ISSUE TITLE
Stuck at "Running hhsearch"

### ISSUE THREAD

**Issue by denizkavi** [baker-laboratory/RoseTTAFold-All-Atom#59]
I used the BLAST change in #31 but now my MSA step stalls at  "Running hhsearch", the machine I'm running has 8 vCPUs and 32GB memory. Seems to be stuck at the waitpid call. Anyone else have a similar problem?
```
(RFAA) ~/RoseTTAFold-All-Atom$ python -m rf2aa.run_inference --config-name protein
/opt/conda/envs/RFAA/lib/python3.10/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'protein': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
Using the cif atom ordering for TRP.
./make_msa.sh examples/protein/7s69_A.fasta 7u7w_protein/A 4 64 /data/UniRef30_2021_06/UniRef30_2021_06 /data/pdb100_2021Mar03/pdb100_2021Mar03
Running PSIPRED
Running hhsearch
^C^CTraceback (most recent call last):
  File "/opt/conda/envs/RFAA/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/RFAA/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 209, in <module>
    main()
  File "/opt/conda/envs/RFAA/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/opt/conda/envs/RFAA/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/opt/conda/envs/RFAA/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/opt/conda/envs/RFAA/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/opt/conda/envs/RFAA/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/opt/conda/envs/RFAA/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 119, in run
    ret = run_job(
  File "/opt/conda/envs/RFAA/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/ubuntu/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 206, in main
    runner.infer()
  File "/home/ubuntu/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 153, in infer
    self.parse_inference_config()
  File "/home/ubuntu/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 46, in parse_inference_config
    protein_input = generate_msa_and_load_protein(
  File "/home/ubuntu/RoseTTAFold-All-Atom/rf2aa/data/protein.py", line 92, in generate_msa_and_load_protein
    msa_file, hhr_file, atab_file = make_msa(fasta_file, chain, model_runner)
  File "/home/ubuntu/RoseTTAFold-All-Atom/rf2aa/data/preprocessing.py", line 33, in make_msa
    _ = subprocess.run(search_command, shell=True)
  File "/opt/conda/envs/RFAA/lib/python3.10/subprocess.py", line 505, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/opt/conda/envs/RFAA/lib/python3.10/subprocess.py", line 1146, in communicate
    self.wait()
  File "/opt/conda/envs/RFAA/lib/python3.10/subprocess.py", line 1209, in wait
    return self._wait(timeout=timeout)
  File "/opt/conda/envs/RFAA/lib/python3.10/subprocess.py", line 1959, in _wait
    (pid, sts) = self._try_wait(0)
  File "/opt/conda/envs/RFAA/lib/python3.10/subprocess.py", line 1917, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```

**Comment by qisheng-pan** [comment]
I got a similar issue... I set `num_cpus=32` to run `hhsearch`, but it got stuck for a whole night... 

I am running a job on the pdb `2JBZ` with the ligand CoA.
