### ISSUE TITLE
Segmentation Fault ; FileNotFoundError: [Errno 2] No such file or directory: '7qxr/A/t000.atab'

### ISSUE THREAD

**Issue by darylrbarth** [baker-laboratory/RoseTTAFold-All-Atom#60]
I added in the Blast fix from #31 which fixed the ss_residue error and now when I try any of the examples it seems the atab file isn't being generated/saved correctly? 
My call is here: 
HYDRA_FULL_ERROR=1 python -m rf2aa.run_inference --config-name protein_sm

And full error output is this: 
./make_msa.sh: line 126: 1748815 Segmentation fault      (core dumped) $HH -i $out_dir/t000_.msa0.ss2.a3m -o $out_dir/t000_.hhr -atab $out_dir/t000_.atab -v 0
Error executing job with overrides: []
Traceback (most recent call last):
File "/stor/home/drb2955/mambaforge/envs/RFAA/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/stor/home/drb2955/mambaforge/envs/RFAA/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/stor/work/Marcotte/project/drbarth/software/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 209, in <module>
main()
File "/stor/home/drb2955/mambaforge/envs/RFAA/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
_run_hydra(
File "/stor/home/drb2955/mambaforge/envs/RFAA/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
_run_app(
File "/stor/home/drb2955/mambaforge/envs/RFAA/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
run_and_report(
File "/stor/home/drb2955/mambaforge/envs/RFAA/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
raise ex
File "/stor/home/drb2955/mambaforge/envs/RFAA/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
return func()
File "/stor/home/drb2955/mambaforge/envs/RFAA/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
lambda: hydra.run(
File "/stor/home/drb2955/mambaforge/envs/RFAA/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
_ = ret.return_value
File "/stor/home/drb2955/mambaforge/envs/RFAA/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
raise self.return_value
File "/stor/home/drb2955/mambaforge/envs/RFAA/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
ret.return_value = task_function(task_cfg)
File "/stor/work/Marcotte/project/drbarth/software/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 206, in main
runner.infer()
File "/stor/work/Marcotte/project/drbarth/software/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 153, in infer
self.parse_inference_config()
File "/stor/work/Marcotte/project/drbarth/software/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 46, in parse_inference_config
protein_input = generate_msa_and_load_protein(
File "/stor/work/Marcotte/project/drbarth/software/RoseTTAFold-All-Atom/rf2aa/data/protein.py", line 93, in generate_msa_and_load_protein
return load_protein(str(msa_file), str(hhr_file), str(atab_file), model_runner)
File "/stor/work/Marcotte/project/drbarth/software/RoseTTAFold-All-Atom/rf2aa/data/protein.py", line 66, in load_protein
xyz_t, t1d, mask_t, _ = get_templates(
File "/stor/work/Marcotte/project/drbarth/software/RoseTTAFold-All-Atom/rf2aa/data/protein.py", line 30, in get_templates
) = parse_templates_raw(ffdb, hhr_fn=hhr_fn, atab_fn=atab_fn)
File "/stor/work/Marcotte/project/drbarth/software/RoseTTAFold-All-Atom/rf2aa/data/parsers.py", line 628, in parse_templates_raw
for l in open(atab_fn, "r").readlines():
FileNotFoundError: [Errno 2] No such file or directory: '7qxr/A/t000.atab'

Any advice on what to try next is most appreciated! Thanks y'all!!

**Comment by weitse-hsu** [comment]
Does anyone have any insights or update in solving this issue? I have the issue of "t000.atab not found" and it occurs unpredictably. For the same protein-ligand binding complex, the issue occurred only from time to time, but I have no clue why this is the case despite the same command for the same inputs.
