### ISSUE TITLE
make_msa.sh error (signalp6, hhblits, hhfilter)

### ISSUE THREAD

**Issue by blacktanktop** [baker-laboratory/RoseTTAFold-All-Atom#7]
I ran Singularity with the following command
```
singularity run --nv -B /gs -B /apps -B /scr ./SE3nv-20240131.sif -m rf2aa.run_inference --config-name protein_complex_sm
```
However, I get the error "signalp6: command not found" and cannot execute it,
How should I deal with this?

I did the following to handle the DB path
- the full path of DB in DB_UR3 and DB_BFD in make_msa.sh
- commented out PIPE_DIR and DB_TEMPL
- full path of pdb100 at hhdb in base.yaml

```
INFO:    squashfs image was compressed with lz4, if it failed to run, please contact image's author
INFO:    squashfs image was compressed with lz4, if it failed to run, please contact image's author
/usr/lib/python3.10/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'protein_complex_sm': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
Using the cif atom ordering for TRP.
./make_msa.sh examples/protein/3fap_A.fasta 3fap/A 4 64 ./pdb100_2021Mar03/pdb100_2021Mar03
./make_msa.sh: line 24: signalp6: command not found
Running HHblits against UniRef30 with E-value cutoff 1e-10
./make_msa.sh: line 50: hhblits: command not found
./make_msa.sh: line 52: hhfilter: command not found
./make_msa.sh: line 53: hhfilter: command not found
grep: 3fap/A/hhblits/t000_.1e-10.id90cov75.a3m: No such file or directory
grep: 3fap/A/hhblits/t000_.1e-10.id90cov50.a3m: No such file or directory
Running HHblits against UniRef30 with E-value cutoff 1e-6
./make_msa.sh: line 50: hhblits: command not found
./make_msa.sh: line 52: hhfilter: command not found
./make_msa.sh: line 53: hhfilter: command not found
grep: 3fap/A/hhblits/t000_.1e-6.id90cov75.a3m: No such file or directory
grep: 3fap/A/hhblits/t000_.1e-6.id90cov50.a3m: No such file or directory
Running HHblits against UniRef30 with E-value cutoff 1e-3
./make_msa.sh: line 50: hhblits: command not found
./make_msa.sh: line 52: hhfilter: command not found
./make_msa.sh: line 53: hhfilter: command not found
grep: 3fap/A/hhblits/t000_.1e-3.id90cov75.a3m: No such file or directory
grep: 3fap/A/hhblits/t000_.1e-3.id90cov50.a3m: No such file or directory
Running HHblits against BFD with E-value cutoff 1e-3
./make_msa.sh: line 84: hhblits: command not found
./make_msa.sh: line 86: hhfilter: command not found
./make_msa.sh: line 87: hhfilter: command not found
grep: 3fap/A/hhblits/t000_.1e-3.bfd.id90cov75.a3m: No such file or directory
grep: 3fap/A/hhblits/t000_.1e-3.bfd.id90cov50.a3m: No such file or directory
cp: cannot stat '3fap/A/hhblits/t000_.1e-3.bfd.id90cov50.a3m': No such file or directory
Running PSIPRED
./make_msa.sh: line 114: 3fap/A/log/make_ss.stdout: No such file or directory
Running hhsearch
cat: 3fap/A/t000_.ss2: No such file or directory
cat: 3fap/A/t000_.msa0.a3m: No such file or directory
./make_msa.sh: line 122: hhsearch: command not found
Error executing job with overrides: []
Traceback (most recent call last):
  File "/PATHTO/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 206, in main
    runner.infer()
  File "/PATHTO/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 153, in infer
    self.parse_inference_config()
  File "/PATHTO/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 46, in parse_inference_config
    protein_input = generate_msa_and_load_protein(
  File "/PATHTO/RoseTTAFold-All-Atom/rf2aa/data/protein.py", line 93, in generate_msa_and_load_protein
    return load_protein(str(msa_file), str(hhr_file), str(atab_file), model_runner)
  File "/PATHTO/RoseTTAFold-All-Atom/rf2aa/data/protein.py", line 56, in load_protein
    msa, ins, taxIDs = parse_a3m(msa_file)
  File "/PATHTO/RoseTTAFold-All-Atom/rf2aa/data/parsers.py", line 415, in parse_a3m
    fstream = open(filename, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '3fap/A/t000_.msa0.a3m'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by amorehead** [comment]
Is `./signalp6_slow_sequential/` the location of a local installation of `signalp6`? I ask because, when I ran the build command `apptainer build SE3nv-20240308.sif build_container.def`, I received the following missing file error:

```bash
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    The %post section will be run under fakeroot
INFO:    Starting build...
INFO:    squashfs image was compressed with lz4, if it failed to run, please contact image's author
INFO:    Verifying bootstrap image SE3nv-20240131.sif
INFO:    Copying ./signalp6_slow_sequential/ to /opt/
FATAL:   While performing build: unable to copy files from host to container fs: while copying [./signalp6_slow_sequential/] to /tmp/build-temp-2353044345/rootfs/opt/: [-fLr ./signalp6_slow_sequential/ /tmp/build-temp-2353044345/rootfs/opt/]: /usr/bin/cp: cannot stat './signalp6_slow_sequential/': No such file or directory
```

**Comment by jmrussell** [comment]
Correct, it's a local copy downloaded directly from the signalp website.

**Comment by komatsuna-san** [comment]
I tried to built an apptainer container for RoseTTAFold-AA (without SignalP 6.0) myself.
https://github.com/baker-laboratory/RoseTTAFold-All-Atom/issues/5#issuecomment-1986850674

**Comment by blacktanktop** [comment]
Thanks @komatsuna-san.
I have successfully built a Conda environment and run RFAA with your def file as a reference

Like your implementation, I also considered signalp6 and PSIPRED unnecessary from the overall implementation, so I did not install them and successfully avoided them by commenting out or adjusting the output names in the relevant parts of make_msa.sh.

cyan: PDB
magenta: RFAA

![3fap rfaa3](https://github.com/baker-laboratory/RoseTTAFold-All-Atom/assets/7370243/62c25299-d01a-402c-8935-6960b8038972)

I posted this results 
https://twitter.com/black_tank_top/status/1766616999105556824

**Comment by amorehead** [comment]
@blacktanktop, would you be able to share your final def file and `make_msa.sh`?

**Comment by blauemond** [comment]
@blacktanktop Would you like to share your self-built conda environment or introduce your running workflow? I have tried many times via conda implementation but failed.

**Comment by ebettler** [comment]
Hello,
to manage to run rf2aa, i install the following conda environment (via miniconda):
conda create -n rfaa python==3.9
conda activate rfaa
conda install singularity
conda install hhsuite pytorch, icecream, scipy, assertpy, openbabel, opt_einsum, dgl, e3nn, deepdiff
pip install hydra-core  #not working via conda

Some packages are from conda-forge !

**Comment by r-krishna** [comment]
hello, @amorehead's contributions have been merged in main. so you should be able to use the current instructions to download all the necessary packages
