### ISSUE TITLE
ValueError: No valid inputs were provided

### ISSUE THREAD

**Issue by merryxiang** [baker-laboratory/RoseTTAFold-All-Atom#75]
I REALLY NEED YOUR HELP. I REALLY NEED RoseTTAFold-All-Atom. After completing the installation steps, I got an error message during runtime.I tried to change the path to an absolute path in "project. yaml", but still received this error message. Can anyone tell me some possible solutions?

(RFAA) good@xy-server:/mnt/mydrive/RoseTTAFold-All-Atom$ sudo /home/good/mambaforge/bin/python -m rf2aa.run_inference --config-name protein
Using the cif atom ordering for TRP.
Error executing job with overrides: []
Traceback (most recent call last):
  File "/mnt/mydrive/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 206, in main
    runner.infer()
  File "/mnt/mydrive/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 153, in infer
    self.parse_inference_config()
  File "/mnt/mydrive/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 93, in parse_inference_config
    raw_data = merge_all(protein_inputs, na_inputs, sm_inputs, residues_to_atomize, deterministic=self.deterministic)
  File "/mnt/mydrive/RoseTTAFold-All-Atom/rf2aa/data/merge_inputs.py", line 174, in merge_all
    raise ValueError("No valid inputs were provided")
**ValueError: No valid inputs were provided**

**Comment by Alain-chavanieu** [comment]
Hello I have the same/close problem. Did you find th solution ? TY (RFAA) bash-4.4$ python -m rf2aa.run_inference --config-name protein
Using the cif atom ordering for TRP.
Error executing job with overrides: []
Traceback (most recent call last):
  File "/disk/IA/rfaa/mambaforge/envs/RFAA/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/disk/IA/rfaa/mambaforge/envs/RFAA/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/disk/IA/rfaa/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 209, in <module>
    main()
  File "/disk/IA/rfaa/mambaforge/envs/RFAA/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/disk/IA/rfaa/mambaforge/envs/RFAA/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/disk/IA/rfaa/mambaforge/envs/RFAA/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/disk/IA/rfaa/mambaforge/envs/RFAA/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/disk/IA/rfaa/mambaforge/envs/RFAA/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/disk/IA/rfaa/mambaforge/envs/RFAA/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/disk/IA/rfaa/mambaforge/envs/RFAA/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/disk/IA/rfaa/mambaforge/envs/RFAA/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/disk/IA/rfaa/mambaforge/envs/RFAA/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/disk/IA/rfaa/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 206, in main
    runner.infer()
  File "/disk/IA/rfaa/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 153, in infer
    self.parse_inference_config()
  File "/disk/IA/rfaa/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 93, in parse_inference_config
    raw_data = merge_all(protein_inputs, na_inputs, sm_inputs, residues_to_atomize, deterministic=self.deterministic)
  File "/disk/IA/rfaa/RoseTTAFold-All-Atom/rf2aa/data/merge_inputs.py", line 174, in merge_all
    raise ValueError("No valid inputs were provided") 
ValueError: No valid inputs were provided

**Comment by epr7142** [comment]
I encountered the same issue when trying to use this title; it appears that it has to do with the way hydra is being configured in run_inference.py

For the following line 214:
@hydra.main(version_base=None, config_path='config/inference')

Hydra will always try to run the .yaml stored inside of /rf2aa/config/inference.
But the default configs that it ships with use relative paths which are not accurate, and its trying to load files in locations that don't exist. 

Try modifying the paths to hardcoded full paths to your input fasta files.

job_name: "7u7w_protein"
protein_inputs: 
  A:
    fasta_file: /your/install/location/RoseTTAFold-All-Atom/examples/protein/7u7w_A.fasta
