### ISSUE TITLE
error while testing the examples 

### ISSUE THREAD

**Issue by Anupam-5** [baker-laboratory/RoseTTAFold-All-Atom#94]
(RFAA) kinshuk@kinshuk-lab:/media/kinshuk/My Book/RoseTTAFold-All-Atom$ python -m rf2aa.run_inference --config-name covalent
/home/kinshuk/anaconda3/envs/RFAA/lib/python3.10/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'covalent': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
Using the cif atom ordering for TRP.
./make_msa.sh examples/protein/7s69_A.fasta 7s69_A/A 4 64  pdb100_2021Mar03/pdb100_2021Mar03
Predicting: 100%|███████████████████████████████████████████████| 1/1 [00:00<00:00,  2.00sequences/s]
Running HHblits against UniRef30 with E-value cutoff 1e-10
- 12:06:19.755 WARNING: Ignoring unknown option Book/RoseTTAFold-All-Atom/uniclust/UniRef30_2021_06

- 12:06:19.755 ERROR: In /opt/conda/conda-bld/hhsuite_1709621322429/work/src/ffindexdatabase.cpp:11: FFindexDatabase:

- 12:06:19.755 ERROR: 	could not open file '/media/kinshuk_cs219.ffdata'

- 12:06:19.758 INFO: Input file = 7s69_A/A/hhblits/t000_.1e-10.a3m

- 12:06:19.758 INFO: Output file = 7s69_A/A/hhblits/t000_.1e-10.id90cov75.a3m

- 12:06:19.758 ERROR: In /opt/conda/conda-bld/hhsuite_1709621322429/work/src/hhfilter.cpp:177: main:

- 12:06:19.758 ERROR: 	could not open file '7s69_A/A/hhblits/t000_.1e-10.a3m'

- 12:06:19.762 INFO: Input file = 7s69_A/A/hhblits/t000_.1e-10.a3m

- 12:06:19.762 INFO: Output file = 7s69_A/A/hhblits/t000_.1e-10.id90cov50.a3m

- 12:06:19.762 ERROR: In /opt/conda/conda-bld/hhsuite_1709621322429/work/src/hhfilter.cpp:177: main:

- 12:06:19.762 ERROR: 	could not open file '7s69_A/A/hhblits/t000_.1e-10.a3m'

grep: 7s69_A/A/hhblits/t000_.1e-10.id90cov75.a3m: No such file or directory
grep: 7s69_A/A/hhblits/t000_.1e-10.id90cov50.a3m: No such file or directory
Running HHblits against UniRef30 with E-value cutoff 1e-6
- 12:06:19.772 WARNING: Ignoring unknown option Book/RoseTTAFold-All-Atom/uniclust/UniRef30_2021_06

- 12:06:19.772 ERROR: In /opt/conda/conda-bld/hhsuite_1709621322429/work/src/ffindexdatabase.cpp:11: FFindexDatabase:

- 12:06:19.772 ERROR: 	could not open file '/media/kinshuk_cs219.ffdata'

- 12:06:19.776 INFO: Input file = 7s69_A/A/hhblits/t000_.1e-6.a3m

- 12:06:19.776 INFO: Output file = 7s69_A/A/hhblits/t000_.1e-6.id90cov75.a3m

- 12:06:19.776 ERROR: In /opt/conda/conda-bld/hhsuite_1709621322429/work/src/hhfilter.cpp:177: main:

- 12:06:19.776 ERROR: 	could not open file '7s69_A/A/hhblits/t000_.1e-6.a3m'

- 12:06:19.780 INFO: Input file = 7s69_A/A/hhblits/t000_.1e-6.a3m

- 12:06:19.780 INFO: Output file = 7s69_A/A/hhblits/t000_.1e-6.id90cov50.a3m

- 12:06:19.780 ERROR: In /opt/conda/conda-bld/hhsuite_1709621322429/work/src/hhfilter.cpp:177: main:

- 12:06:19.780 ERROR: 	could not open file '7s69_A/A/hhblits/t000_.1e-6.a3m'

grep: 7s69_A/A/hhblits/t000_.1e-6.id90cov75.a3m: No such file or directory
grep: 7s69_A/A/hhblits/t000_.1e-6.id90cov50.a3m: No such file or directory
Running HHblits against UniRef30 with E-value cutoff 1e-3
- 12:06:19.791 WARNING: Ignoring unknown option Book/RoseTTAFold-All-Atom/uniclust/UniRef30_2021_06

- 12:06:19.791 ERROR: In /opt/conda/conda-bld/hhsuite_1709621322429/work/src/ffindexdatabase.cpp:11: FFindexDatabase:

- 12:06:19.791 ERROR: 	could not open file '/media/kinshuk_cs219.ffdata'

- 12:06:19.795 INFO: Input file = 7s69_A/A/hhblits/t000_.1e-3.a3m

- 12:06:19.795 INFO: Output file = 7s69_A/A/hhblits/t000_.1e-3.id90cov75.a3m

- 12:06:19.795 ERROR: In /opt/conda/conda-bld/hhsuite_1709621322429/work/src/hhfilter.cpp:177: main:

- 12:06:19.795 ERROR: 	could not open file '7s69_A/A/hhblits/t000_.1e-3.a3m'

- 12:06:19.799 INFO: Input file = 7s69_A/A/hhblits/t000_.1e-3.a3m

- 12:06:19.799 INFO: Output file = 7s69_A/A/hhblits/t000_.1e-3.id90cov50.a3m

- 12:06:19.799 ERROR: In /opt/conda/conda-bld/hhsuite_1709621322429/work/src/hhfilter.cpp:177: main:

- 12:06:19.799 ERROR: 	could not open file '7s69_A/A/hhblits/t000_.1e-3.a3m'

grep: 7s69_A/A/hhblits/t000_.1e-3.id90cov75.a3m: No such file or directory
grep: 7s69_A/A/hhblits/t000_.1e-3.id90cov50.a3m: No such file or directory
Running HHblits against BFD with E-value cutoff 1e-3
- 12:06:19.809 WARNING: Ignoring unknown option Book/RoseTTAFold-All-Atom/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt

- 12:06:19.809 ERROR: In /opt/conda/conda-bld/hhsuite_1709621322429/work/src/ffindexdatabase.cpp:11: FFindexDatabase:

- 12:06:19.809 ERROR: 	could not open file '/media/kinshuk_cs219.ffdata'

- 12:06:19.813 INFO: Input file = 7s69_A/A/hhblits/t000_.1e-3.bfd.a3m

- 12:06:19.813 INFO: Output file = 7s69_A/A/hhblits/t000_.1e-3.bfd.id90cov75.a3m

- 12:06:19.813 ERROR: In /opt/conda/conda-bld/hhsuite_1709621322429/work/src/hhfilter.cpp:177: main:

- 12:06:19.813 ERROR: 	could not open file '7s69_A/A/hhblits/t000_.1e-3.bfd.a3m'

- 12:06:19.818 INFO: Input file = 7s69_A/A/hhblits/t000_.1e-3.bfd.a3m

- 12:06:19.818 INFO: Output file = 7s69_A/A/hhblits/t000_.1e-3.bfd.id90cov50.a3m

- 12:06:19.818 ERROR: In /opt/conda/conda-bld/hhsuite_1709621322429/work/src/hhfilter.cpp:177: main:

- 12:06:19.818 ERROR: 	could not open file '7s69_A/A/hhblits/t000_.1e-3.bfd.a3m'

grep: 7s69_A/A/hhblits/t000_.1e-3.bfd.id90cov75.a3m: No such file or directory
grep: 7s69_A/A/hhblits/t000_.1e-3.bfd.id90cov50.a3m: No such file or directory
cp: cannot stat '7s69_A/A/hhblits/t000_.1e-3.bfd.id90cov50.a3m': No such file or directory
Running PSIPRED
Running hhsearch
cat: 7s69_A/A/t000_.ss2: No such file or directory
cat: 7s69_A/A/t000_.msa0.a3m: No such file or directory
- 12:06:19.940 ERROR: Error in /opt/conda/conda-bld/hhsuite_1709621322429/work/src/hhfunc.cpp:16: ReadQueryFile:

- 12:06:19.940 ERROR: 	7s69_A/A/t000_.msa0.ss2.a3m is empty!

Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/kinshuk/anaconda3/envs/RFAA/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/kinshuk/anaconda3/envs/RFAA/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/media/kinshuk/My Book/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 209, in <module>
    main()
  File "/home/kinshuk/anaconda3/envs/RFAA/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/kinshuk/anaconda3/envs/RFAA/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/kinshuk/anaconda3/envs/RFAA/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/kinshuk/anaconda3/envs/RFAA/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/kinshuk/anaconda3/envs/RFAA/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/kinshuk/anaconda3/envs/RFAA/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/kinshuk/anaconda3/envs/RFAA/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/kinshuk/anaconda3/envs/RFAA/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/kinshuk/anaconda3/envs/RFAA/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/media/kinshuk/My Book/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 206, in main
    runner.infer()
  File "/media/kinshuk/My Book/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 153, in infer
    self.parse_inference_config()
  File "/media/kinshuk/My Book/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 46, in parse_inference_config
    protein_input = generate_msa_and_load_protein(
  File "/media/kinshuk/My Book/RoseTTAFold-All-Atom/rf2aa/data/protein.py", line 93, in generate_msa_and_load_protein
    return load_protein(str(msa_file), str(hhr_file), str(atab_file), model_runner)
  File "/media/kinshuk/My Book/RoseTTAFold-All-Atom/rf2aa/data/protein.py", line 56, in load_protein
    msa, ins, taxIDs = parse_a3m(msa_file)
  File "/media/kinshuk/My Book/RoseTTAFold-All-Atom/rf2aa/data/parsers.py", line 415, in parse_a3m
    fstream = open(filename, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '7s69_A/A/t000_.msa0.a3m'

I followed the installation strictly but encuntered this error. Please help..

**Comment by rukibuki** [comment]
There are multiple issues on this.
but take a look here: https://github.com/baker-laboratory/RoseTTAFold-All-Atom/issues/72#issuecomment-2047914460
